EVT.TaskManager.MVC/Models/ErrorViewModel.cs
namespace EVT.TaskMamager.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EVT.TaskManager.MVC/Models/LoginPartialViewModel.cs
using EVT.TaskManager.ModelEntities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EVT.TaskMamager.MVC.Models
{
    public class LoginPartialViewModel : PageModel
    {
        private readonly SignInManager<UserBase> _signInManager;
        private readonly UserManager<UserBase> _userManager;

        public bool IsUserSignedIn { get => _signInManager.IsSignedIn(User); }
        public LoginPartialViewModel(SignInManager<UserBase> signInManager,  UserManager<UserBase> userManager)
        {
            _signInManager=signInManager;
            _userManager=userManager;
        }

    }
}

EVT.TaskManager.MVC/Areas/Messages/Pages/NotFound_404.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EVT.TaskMamager.MVC.Areas.Messages.Pages
{
    public class NotFound_404Modell : PageModel
    {
        public void OnGet()
        {
        }
    }
}

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/TaskList.cshtml.cs
using EVT.TaskManager.DataObjectInterfaces;
using EVT.TaskManager.Entities;
using EVT.TaskManager.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EVT.TaskMamager.MVC.Areas.ModelEntities.Pages
{
    public class TaskListModel: PageModel
    {
        private readonly ILogger<TaskListModel> _logger;
        private readonly IDBManager _dbManager;
        public TaskListModel(ILogger<TaskListModel> logger, IDBManager dbManager)
        {
            _logger = logger;
            _dbManager = dbManager;
        }


        public IEnumerable<TaskBase> Tasks;

        public async Task<IActionResult> OnGetAsync()
        {
            Tasks = await _dbManager.GetEntitiesAsync<TaskBase>();
            return Page();
        }
    }
}

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/UserList.cshtml.cs
using EVT.TaskManager.DataObjectInterfaces;
using EVT.TaskManager.Entities;
using EVT.TaskManager.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EVT.TaskMamager.MVC.Areas.ModelEntities.Pages
{
    public class UserListModel : PageModel
    {

        private readonly ILogger<UserListModel> _logger;
        private readonly IDBManager _dbManager;
        private readonly UserManager<UserBase> _manager;


        #region Binding
        [BindProperty]
        public VisualItem[] VisualItems { get; set; }
        
        #endregion

        #region C-tor
        public UserListModel(ILogger<UserListModel> logger, IDBManager dbManager, UserManager<UserBase> manager)
        {
            _logger = logger;
            _dbManager= dbManager;
            _manager = manager;
        }
        #endregion


        #region Requests

        public void OnGet()
        {
            var list = new List<VisualItem>();
            foreach (var item in _manager.Users)
            {
                list.Add(new VisualItem() { ID = item.Id, IsSelected = false, User=item });
            }

            VisualItems = list.ToArray();

        }


        public IActionResult OnPostDeactivateUsers()
        {
            foreach (var item in VisualItems)
            {
                //if (item.IsSelected) _facade.Deactivate(item.User); 
            }
            return RedirectToPage();
        }

        #endregion


        public class VisualItem
        {

            public string ID { get; set; }

            public bool IsSelected { get; set; }

            public UserBase User { get; set; }

        }



    }
}

EVT.TaskManager.MVC/Controllers/HomeController.cs
using EVT.TaskMamager.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EVT.TaskMamager.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/NewTask.cshtml
@page
@model EVT.TaskMamager.MVC.Areas.ModelEntities.NewTaskModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "NewTask";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container tm-container-max-800" id="newtask">
    <div class="validation" asp-validation-summary="All"></div>
    <div class="row">
        <h3> Новая задача для: </h3>

    </div>

    <form method="post" asp-antiforgery="true">
        <div class="tm-bg-black tm-form-block">
            <div class="row mb-4">
                <div class="col-xl-6">
                    <div class="input-field m-4">
                        @{
                            if (Model.HandlerUserName == null)
                            {
                                <select asp-items="@Model.HandlersList">
                                </select>
                            }
                            else
                            {
                                <input asp-for="HandlerUserName" placeholder="@Model.HandlerUserName">
                                <label asp-for="HandlerUserName">Ответственный</label>
                            }
                        }
                    </div>
                    <div class="input-field">
                        <input asp-for="TaskTitle" placeholder="Наименование">
                        <span asp-validation-for="TaskTitle"></span>
                    </div>
                    <div class="input-field">
                        <textarea class="p-3" asp-for="Description" cols="30" rows="3" placeholder="Дополнительное описание..."></textarea>
                    </div>

                    <div class="input-group date" data-provide="datepicker">
                        <input type="text" class="form-control">
                        <div class="input-group-addon" >
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>


                </div>


            </div>
            <button type="submit" class="waves-effect btn-large btn-large-white px-4 black-text rounded-0">Создать</button>
        </div>
    </form>
</div>

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/TaskEdit.cshtml
@page
@model EVT.TaskMamager.MVC.Areas.ModelEntities.Pages.TaskEditModel
@{
}
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "TaskEdit";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<div class="container tm-container-max-800" id="taskedit">
    <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
        <div class="toast" id="toastNotice" style="position: absolute; top: 0; right: 0;" data-delay="2000">
            <div class="toast-header">
                <img src="..." class="rounded mr-2" alt="...">
                <strong class="mr-auto">@Model.Message</strong>
                <small>11 mins ago</small>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
    @*<div class="validation" asp-validation-summary="All"></div> *@
    <form method="post" asp-antiforgery="true">
        <div class="tm-bg-black tm-form-block">
            <div class="row mb-4">
                <div class="col-xl-6">
                    <div class="input-field">
                        <label asp-for="CurrentTask.Title" class="col-form-label"></label>
                        <input asp-for="CurrentTask.Title" value=@Model.CurrentTask.Title>
                        <span asp-validation-for="CurrentTask.Title"></span>
                    </div>

                    <div class="input-field">
                        <label asp-for="CurrentTask.Description" class="col-form-label"></label>
                        <input asp-for="CurrentTask.Description" value=@Model.CurrentTask.Description>
                        <span asp-validation-for="CurrentTask.Description"></span>
                    </div>

                    <div class="input-field">
                        <label asp-for="CurrentTask.SubmitterViewName" class="col-form-label"></label>
                        <input asp-for="CurrentTask.SubmitterViewName" value=@Model.CurrentTask.SubmitterViewName readonly>
                    </div>

                    <div class="input-field">
                        <label asp-for="CurrentTask.HandlerViewName" class="col-form-label"></label>
                        <select asp-for="CurrentTask.HandlerViewName" asp-items="Model.UserList" value="@Model.CurrentTask.HandlerViewName">                    
                           @* <option selected="selected" value="@Model.HandlerUserName">@Model.HandlerUserFullName</option>*@
                        </select>
                    </div>

                    <div class="input-field">
                        <label asp-for="CurrentTask.CreationDate" class="col-form-label"></label>
                        <input asp-for="CurrentTask.CreationDate" value=@Model.CurrentTask.CreationDate readonly>
                    </div>

                    <div class="input-field">
                        <label asp-for="CurrentTask.UpdateDate" class="col-form-label"></label>
                        <input asp-for="CurrentTask.UpdateDate" value=@Model.CurrentTask.UpdateDate readonly>
                    </div>

                    <div class="input-field">
                        <label asp-for="CurrentTask.DeadlineDate" class="col-form-label"></label>
                        <input asp-for="CurrentTask.DeadlineDate" value=@Model.CurrentTask.DeadlineDate>
                        <span asp-validation-for="CurrentTask.DeadlineDate"></span>
                    </div>

                    <div class="input-field">
                        <label asp-for="CurrentTask.CloseDate" class="col-form-label"></label>
                        <input asp-for="CurrentTask.CloseDate" value=@Model.CurrentTask.CloseDate readonly>
                    </div>

                </div>



            </div>
            <button id="saveChangesBtn" type="submit" class="waves-effect btn-large btn-large-white px-4 black-text rounded-0" asp-route-id="@Model.CurrentTask.Id">Сохранить изменения</button>
        </div>
    </form>
</div>

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/TaskList.cshtml
@page
@model EVT.TaskMamager.MVC.Areas.ModelEntities.Pages.TaskListModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>TaskList</h1>


<table class="table table-hover">
    <thead class="thead-default">
        <tr>
            <th class="text-center py-1">Дата создания</th>
            <th>Название</th>
            <th>Описание</th>
            <th class="text-center py-1">Статус</th>
            <th class="text-center py-1">Автор</th>
            <th class="text-center py-1">Ответственный</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Tasks)
        {
            <tr>
                <td class="text-center py-1">@item.CreationDate</td>
                <td>
                    <a class="btn btn-outline-primary btn-xs" asp-page="/TaskEdit" asp-route-id="@item.Id">@item.Title</a>
                </td>

                <td>@item.Description</td>
                <td class="text-center py-1">@item.Status</td>
                <td class="text-center py-1">
                    <a asp-page="/UserProfile">@item.Submitter</a>
                </td>
                <td class="text-center py-1">
                <a asp-page="/UserProfile">@item.Handler</a>
                </td>
            </tr>
        }
    </tbody>
</table>

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/UserList.cshtml
@page
@model EVT.TaskMamager.MVC.Areas.ModelEntities.Pages.UserListModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "UserList";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>UserList</h1>
<h3>@Model.VisualItems.Count()</h3>
@* @{
    <div class="row">
    @foreach (var item in Model.Users)
    {
    <div class="col-12 col-sm-6 col-lg-4">
    <div class="card-dec">
    <div class="card m-3">
    <div class="card-header text-center">
    <h3>@item.FullName</h3>
    </div>
    <div class="text-center">
    <h3>@item.Login</h3>
    </div>
    <div class="card-footer text-center">
    <a href="#" class="btn btn-success m-1">View</a>
    </div>
    </div>
    </div>
    </div>
    }
    </div>
    } *@


    <div class="row">
        <form method="post" asp-page-handler="DeactivateUsers">
            <table class="table table-hover">
                <thead class="thead-default">
                    <tr>
                        <th> </th>
                        <th> </th>
                        <th class="text-center py-1">Дата регистарации</th>
                        <th class="text-center py-1">Логин</th>
                        <th class="text-center py-1">Полное имя</th>
                        <th class="text-center py-1">Email</th>
                        <th class="text-center py-1">Роль</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.VisualItems.Count(); i++)
                    {
                        var item = Model.VisualItems[i];
                        if (!item.User.IsActive) continue;
                        <tr>
                            <td>
                                <label class="container">
                                    <input asp-for="VisualItems[i].ID"  type="hidden">
                                </label>
                            </td>
                            <td>
                                <label class="container">
                                    <input asp-for="VisualItems[i].IsSelected" class="filled-in">
                                    <span class="checkmark"></span>
                                </label>
                            </td>
                            <td class="text-center py-1">@item.User.RegistrationDate</td>
                            <td class="text-center py-1">
                                <a class="btn btn-outline-primary btn-xs" asp-page="/UserProfile" asp-route-name="@item.User.UserName">@item.User.UserName</a>
                            </td>
                            <td class="text-center py-1">@item.User.FullName</td>
                            <td class="text-center py-1">@item.User.Email</td>
                            <td class="text-center py-1"></td> @* @item.User.UserRole *@
                        </tr>
                    }
                </tbody>
            </table>
            <div class="text-left mt-4">
                <button type="submit" class="waves-effect btn-large btn-large-white px-4 tm-border-radius-0">Удалить</button>
            </div>
        </form>
    </div>

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/UserProfile.cshtml
@page "{name}"
@model EVT.TaskMamager.MVC.Areas.ModelEntities.Pages.UserProfileModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "ЮзверьProfile";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<div class="tm-container" id="userprofile">

    <div class="row">
        <div class="col-4">
            <h3>@Model.CurrentUser.UserName</h3>
            <form method="get" class="tm-form-white tm-font-big">
                <div class="tm-bg-white tm-form-pad-same-small">
                    @*
                        <div class="row">
                        <label for="name" class="black-text mb-4 big">Full Name</label>
                        <input asp-for="CurrentUser.FullName" readonly value="@Model.CurrentUser.FullName">
                        </div>
                    *@
                    <div class="input-group mb-3">
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">ФИО пользователя</label>
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">@Model.CurrentUser.FullName</label>
                    </div>
                    <div class="input-group mb-3">
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Email</label>
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">@Model.CurrentUser.Email</label>
                    </div>
                    <div class="input-group mb-3">
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Дата регистрации</label>
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">@Model.CurrentUser.RegistrationDate</label>
                    </div>
                    <div class="input-group mb-3">
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">Роль</label>
                        <label for="name" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">@Model.Roles</label>   
                    </div>
                </div>
                <div class="text-center mt-5">
                    <a  class="waves-effect btn-large btn-large-white" asp-page="/UserProfileEdit" asp-route-name="@Model.CurrentUser.UserName">Редактировать</a>

                </div>
            </form>

        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="post" class="tm-form-white tm-font-big">
                <div class="row">
                    <h3>Текущие задачи</h3>
                    <a class="btn btn-flat" asp-page="/NewTask" asp-route-name="@Model.CurrentUser.UserName">Создать</a>
                </div>
                <input type="hidden" asp-for="CurrentUser.Id" />
                <table class="table table-hover">
                    <thead class="thead-default">
                        <tr>
                            <th class="text-center py-1">Дата создания</th>
                            <th>Название</th>
                            <th>Описание</th>
                            <th class="text-center py-1">Статус</th>
                            <th class="text-center py-1">Автор</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Tasks)
                        {
                            <tr>
                                <td class="text-center py-1">@item.CreationDate</td>
                                <td>
                                    <a class="btn btn-outline-primary btn-xs" asp-page="/TaskEdit" asp-route-id="@item.Id">@item.Title</a>
                                </td>

                                <td>@item.Description</td>
                                <td class="text-center py-1">@item.Status</td>
                                <td class="text-center py-1">
                                    <a>@item.Submitter</a>
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>




            </form>
        </div>
    </div>
</div>

EVT.TaskManager.MVC/Areas/ModelEntities/Pages/UserProfileEdit.cshtml
@page 
@model EVT.TaskMamager.MVC.Areas.ModelEntities.Pages.UserProfileEditModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "UserProfileEdit";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<style>
    body {
        background-image: url(../img/input-bg-06.jpg);
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center top;
    }
</style>



<div class="container tm-container-max-800">

    <h1> @Model.PageHeader  </h1>
    @*
        <form >
        <div class="row text-center">
        <h2></h2>
        <input asp-for="Notify" class="for-check-input" />
        <label asp-for="Notify" class="form-check-label">
        Отправлять на емайл изменения профиля
        </label> <br />
        <button type="submit" class="btn btn-primary">
        Update
        </button>
        @if (!string.IsNullOrWhiteSpace(Model.Message))
        {
        <div class="alert alert-cuccess">
        <p class="p-3 mt-2">@Model.Message</p>
        </div>
        }
        </div>
        </form>
        <hr />
        <div asp-validation-summary="All" class="text-danger text-center"></div>

    *@
    @*

    <form method="post">
        <input type="hidden" asp-for="CurrentUser.Id" />
        <div class="tm-bg-black tm-form-block">
            <div class="row mb-4">
                <div class="col-xl-6">
                    @*
                        <div class="row mb-3">
                        <label class="col-sm-2 col-form-label col-form-label-sm">Логин</label>
                        <div class="col-sm-4">
                        <label asp-for="CurrentUser.Login" class="form-label">Имя аккаунта</label>
                        <input type="text" class="form-control form-control-sm" id="txtLogin" value=@Model.CurrentUser.Login>

                        </div>
                        </div>
                    *@
                    @*
                    <div class="input-field">
                        <input asp-for="CurrentUser.AccountName" placeholder="@Model.CurrentUser.AccountName">
                    </div>
                    <div class="input-field">
                        <input asp-for="CurrentUser.FullName" placeholder="@Model.CurrentUser.FullName">
                    </div>
                    <div class="input-field">
                        <input asp-for="CurrentUser.Email" placeholder="@Model.CurrentUser.Email">
                    </div>
                    @*
                    <div class="input-field mb-5">
                        <input asp-for="CurrentUser.Password" type="password" placeholder="Password">
                    </div>

                    *@

                    @*
                    <div class="input-field">
                        <select asp-items="Model.UserRoleList">
                        </select>

                    </div>

                </div>


            </div>
            <div class="row">
                @*
                    <div class="col-xl-12">
                    <textarea class="p-3" cols="30" rows="2" placeholder="Additional Information...(optional)"></textarea>
                    </div>
                *@
                @*
            </div>
            <button type="submit" class="btn btn-primary">
                Сохранить изменения
            </button>
        </div>
    </form>
  *@
</div>